// ── Community Addon Registry ──────────────────────────────────────────────────
// Curated list of community addons that users can install.
// Each addon is a JSON manifest + optional JS module.

export const COMMUNITY_ADDONS = [
  {
    id: "vidcloud",
    name: "VidCloud",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream from VidCloud (vidcloud.pro)",
    author: "Community",
    builtIn: false,
    manifest: {
      id: "vidcloud",
      name: "VidCloud",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream from VidCloud",
      movieUrl: (id) => `https://vidcloud.pro/movie/${id}`,
      tvUrl: (id, s, e) => `https://vidcloud.pro/tv/${id}/${s}/${e}`,
      supportsProgress: true,
    },
  },
  {
    id: "moviesapi",
    name: "MoviesAPI",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream from MoviesAPI (moviesapi.to)",
    author: "Community",
    builtIn: false,
    manifest: {
      id: "moviesapi",
      name: "MoviesAPI",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream from MoviesAPI",
      movieUrl: (id) => `https://moviesapi.to/movie/${id}`,
      tvUrl: (id, s, e) => `https://moviesapi.to/tv/${id}/${s}/${e}`,
      supportsProgress: true,
    },
  },
  {
    id: "streamflix",
    name: "StreamFlix",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream from StreamFlix (streamflix.to)",
    author: "Community",
    builtIn: false,
    manifest: {
      id: "streamflix",
      name: "StreamFlix",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream from StreamFlix",
      movieUrl: (id) => `https://streamflix.to/movie/${id}`,
      tvUrl: (id, s, e) => `https://streamflix.to/tv/${id}/${s}/${e}`,
      supportsProgress: true,
    },
  },
  {
    id: "animeultima",
    name: "AnimeUltima",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream anime from AnimeUltima",
    author: "Community",
    builtIn: false,
    tag: "ANIME",
    manifest: {
      id: "animeultima",
      name: "AnimeUltima",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream anime from AnimeUltima",
      tag: "ANIME",
      movieUrl: (_id) => "https://animeultima.to",
      tvUrl: (_id, _s, _e) => "https://animeultima.to",
      supportsProgress: true,
      async: true,
    },
  },
  {
    id: "kickassanime",
    name: "KickAssAnime",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream anime from KickAssAnime",
    author: "Community",
    builtIn: false,
    tag: "ANIME",
    manifest: {
      id: "kickassanime",
      name: "KickAssAnime",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream anime from KickAssAnime",
      tag: "ANIME",
      movieUrl: (_id) => "https://kickassanime.rs",
      tvUrl: (_id, _s, _e) => "https://kickassanime.rs",
      supportsProgress: true,
      async: true,
    },
  },
  {
    id: "animefreak",
    name: "AnimeFreak",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream anime from AnimeFreak",
    author: "Community",
    builtIn: false,
    tag: "ANIME",
    manifest: {
      id: "animefreak",
      name: "AnimeFreak",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream anime from AnimeFreak",
      tag: "ANIME",
      movieUrl: (_id) => "https://animefreak.xyz",
      tvUrl: (_id, _s, _e) => "https://animefreak.xyz",
      supportsProgress: true,
      async: true,
    },
  },
  {
    id: "animedao",
    name: "AnimeDao",
    version: "1.0.0",
    type: "stream-source",
    description: "Stream anime from AnimeDao",
    author: "Community",
    builtIn: false,
    tag: "ANIME",
    manifest: {
      id: "animedao",
      name: "AnimeDao",
      version: "1.0.0",
      type: "stream-source",
      description: "Stream anime from AnimeDao",
      tag: "ANIME",
      movieUrl: (_id) => "https://animedao.to",
      tvUrl: (_id, _s, _e) => "https://animedao.to",
      supportsProgress: true,
      async: true,
    },
  },
];
